# Pre-commit hooks for security and code quality
# Install: pip install pre-commit
# Setup: pre-commit install

repos:
  - repo: local
    hooks:
      - id: check-secrets
        name: Check for hardcoded secrets
        entry: ./scripts/check-secrets.sh
        language: script
        pass_filenames: false
        
      - id: no-commit-secrets
        name: Block commits with secrets files
        entry: bash -c 'if ls configs/secrets/*.secrets.yaml 2>/dev/null; then echo "Error: Secrets files found in configs/secrets/"; exit 1; fi'
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-vet
      - id: go-mod-tidy

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']