# 核心服务 - 仅本地镜像
services:
  # 项目服务
  project-service:
    image: project-service:runtime
    container_name: devcollab-project
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 15432
      POSTGRES_DB: devcollab_production
      POSTGRES_USER: devcollab_prod_user
      POSTGRES_PASSWORD: devcollab_prod_pass
      REDIS_HOST: localhost
      REDIS_PORT: 16379
      REDIS_PASSWORD: redis_prod_pass_123
      JWT_SECRET_KEY: super-secure-jwt-key-for-production-environment-32characters
      GIN_MODE: release
      LOG_LEVEL: INFO
    ports:
      - "8002:8080"
    networks:
      - devcollab-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  devcollab-prod:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16