global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'devcollab-prod-monitor'

rule_files:
  - "devcollab_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'iam-service'
    static_configs:
      - targets: ['iam-service:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'project-service'
    static_configs:
      - targets: ['localhost:8082']
    metrics_path: /api/v1/metrics
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:15432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:16379']
    scrape_interval: 30s