# Cloud-Based Collaborative Development Platform
# 应用程序配置文件

# 服务器配置
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  environment: "development"

# 数据库配置
database:
  host: "localhost"
  port: 5432
  name: "devcollab_development"
  user: "devcollab_dev"
  password: "${DATABASE_PASSWORD}"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "300s"
  conn_max_idle_time: "60s"

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  pool_size: 10
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

# Kafka配置
kafka:
  brokers:
    - "localhost:9092"
  group_id: "collaborative-platform"

# 认证配置
auth:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiration: "24h"
  refresh_token_expiry: "168h"  # 7天
  password_min_length: 8
  max_login_attempts: 5
  lockout_duration: "15m"
  session_timeout: "30m"
  two_factor_enabled: false

# 日志配置
log:
  level: "info"
  format: "json"
  output: "stdout"
  max_size: 100    # MB
  max_backups: 3
  max_age: 28      # 天
  compress: true

# 监控配置
monitor:
  enabled: true
  metrics_port: 9090
  tracing_enabled: true
  tracing_endpoint: "http://localhost:14268/api/traces"
  sampling_rate: 0.1

# 邮件配置
email:
  smtp_host: "smtp.company.com"
  smtp_port: 587
  username: "${EMAIL_USERNAME}"
  password: "${EMAIL_PASSWORD}"
  from_address: "noreply@company.com"
  from_name: "Collaborative Platform"

# 缓存配置
cache:
  default_ttl: "1h"
  cleanup_interval: "10m"
  max_entries: 1000

# 限流配置
rate_limit:
  enabled: true
  requests_per_minute: 60
  burst_size: 10

# 安全配置
security:
  cors_allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  trusted_proxies:
    - "127.0.0.1"
    - "10.0.0.0/8"
  max_request_size: "10MB"

# 功能开关
features:
  enable_metrics: true
  enable_tracing: true
  enable_audit_log: true
  enable_2fa: false
  enable_webhook: true

# CI/CD服务配置
cicd:
  scheduler:
    worker_count: 5
    queue_size: 1000
    poll_interval: "10s"
    job_timeout: "30m"
    max_retries: 3
    enable_priority: true
    enable_load_balance: true
  
  runner:
    pool_size: 10
    heartbeat_interval: "30s"
    max_idle_time: "5m"
    enable_auto_scale: false
  
  executor:
    max_concurrent_jobs: 10
    default_timeout: "30m"
    enable_auto_cleanup: true

# 存储配置
storage:
  type: "local"  # local, s3, minio
  local:
    base_path: "/var/lib/cicd/storage"
    max_file_size: 104857600  # 100MB
    allowed_exts: [".tar.gz", ".zip", ".log", ".txt"]
  s3:
    region: "us-east-1"
    bucket: "collaborative-platform-storage"
    access_key_id: "${STORAGE_ACCESS_KEY}"
    secret_access_key: "${STORAGE_SECRET_KEY}"
    endpoint: ""
    use_ssl: true
  cache:
    type: "memory"
    ttl: "30m"
    max_size: 52428800      # 50MB
    max_entries: 1000
  artifact:
    retention_days: 30
    max_size_per_job: 524288000   # 500MB
    max_total_size: 10737418240   # 10GB
    compression_type: "gzip"

---
# 生产环境配置覆盖
production:
  server:
    environment: "production"
  
  database:
    ssl_mode: "require"
    max_open_conns: 50
    max_idle_conns: 10
  
  redis:
    pool_size: 20
  
  log:
    level: "warn"
    output: "file"
    file_path: "/var/log/collaborative-platform/app.log"
  
  auth:
    two_factor_enabled: true
  
  security:
    cors_allowed_origins:
      - "https://app.company.com"
    trusted_proxies:
      - "10.0.0.0/8"
  
  features:
    enable_2fa: true

---
# 测试环境配置覆盖
test:
  server:
    environment: "test"
  
  database:
    name: "devcollab_test"
    max_open_conns: 5
  
  redis:
    db: 1
  
  log:
    level: "debug"
  
  auth:
    jwt_expiration: "1h"
  
  features:
    enable_metrics: false
    enable_tracing: false