# Development Environment Configuration
# This file contains development-specific settings

server:
  port: 8080
  environment: development
  read_timeout: 30s
  write_timeout: 30s

database:
  host: localhost
  port: 5432
  name: devcollab_development
  user: devcollab_dev
  ssl_mode: disable
  max_open_conns: 10
  max_idle_conns: 5

redis:
  host: localhost
  port: 6379
  db: 0

kafka:
  brokers:
    - localhost:9092

auth:
  password_min_length: 8
  max_login_attempts: 10
  lockout_duration: 5m
  two_factor_enabled: false

log:
  level: debug
  format: text
  output: stdout

monitor:
  enabled: true
  metrics_port: 9090
  tracing_enabled: true
  tracing_endpoint: http://localhost:14268/api/traces
  sampling_rate: 1.0  # 100% sampling in development

security:
  cors_allowed_origins:
    - http://localhost:3000
    - http://localhost:3003
    - http://localhost:8080
  trusted_proxies:
    - 127.0.0.1
    - ::1

storage:
  type: local
  local:
    base_path: ./data/storage
    max_file_size: 52428800  # 50MB
    allowed_exts:
      - .go
      - .js
      - .ts
      - .jsx
      - .tsx
      - .py
      - .java
      - .cpp
      - .c
      - .h
      - .hpp
      - .cs
      - .rb
      - .php
      - .swift
      - .kt
      - .rs
      - .md
      - .txt
      - .json
      - .yaml
      - .yml
      - .xml
      - .html
      - .css
      - .scss
      - .sass
      - .less

cicd:
  scheduler:
    worker_count: 2
    queue_size: 100
    poll_interval: 5s
    job_timeout: 10m
    max_retries: 2
  runner:
    pool_size: 5
    heartbeat_interval: 30s
    max_idle_time: 5m
  executor:
    max_concurrent_jobs: 5
    default_timeout: 10m
    enable_auto_cleanup: true